### ISSUE TITLE
Error installing Stencila for RStudio

### ISSUE THREAD

**Issue by apawlik** [stencila/r#17]
After installing Stencila for RStudio via `devtools::install_github("stencila/r", ref="develop")` trying to use the AddIn in RStudio returns an error
`Error in `Encoding<-`(`*tmp*`, value = "UTF-8") : a character vector argument expected`

**Comment by nokome** [comment]
Thanks for the bug report @apawlik. Could you try using the "master" branch - there may have been some recent changes that have broken the add-in. 

There are some updated instructions in the getting started guide: https://github.com/stencila/r/blob/master/getting-started.md

I just tried using the add-in when opening the "rodent ' example doc: https://github.com/stencila/examples/tree/master/rodents. Note that you need to have the doc open in RStudio before you use the "Open In Stencila" addin.

Improvements to instructions would be very welcome!

**Comment by nokome** [comment]
Closing this issue. We'll do another round of installation testing soon.
