### ISSUE TITLE
How to merge two barplots in R

### ISSUE THREAD

**Issue by MariaZhi** [stencila/r#38]
Hi,
I am quite new in R !! and i am trying to learn how to plot using R given that it is the best tool for plotting.
My script is not so perfect and I would like to have your advice on how to make it simpler and more automated.

I have two data different datasets with variables (they do not match between both sets), the log of the median value (used for scale) and car percentage (percentage of cars for each variable):

d1:

variable | log_median | car_percentage
-- | -- | --
1 | -0.9133612 | 1
2 | -1.0603856 | 0.83810888
3 | -0.1779693 | 0.4713467
5 | -0.3073219 | 1
8 | -0.0652583 | 0.01862464
9 | -0.2850852 | 0.00573066
13 | -1.0128372 | 0.83381089
17 | -1.1453479 | 0.02005731
18 | -0.9076425 | 0.4713467
21 | 0.286662 | 0.00143266
26 | 0.33405882 | 0.00573066

d2:

variable | log_median | car_percentage
-- | -- | --
1 | 0.43073252 | 0.09090909
2 | 0.30946316 | 0.39772727
3 | 0.2369125 | 0.28977273
5 | 0.15575268 | 0.48863636
10 | 1.72587962 | 0.00568182
13 | 0.31361912 | 0.36931818
19 | 0.99486036 | 0.00568182
26 | 1.22286942 | 0.00568182
45 | 0.22184875 | 0.01136364
79 | 0.02882633 | 0.01136364

1) I plot d1:
gp<- ggplot(d1, aes(x=variable, y=car_percentage, fill=log_median)) + 
  geom_bar(position="dodge", stat="identity", color="black") +
  labs(x="", y = "car percentage", fill="Log (median)") +
  scale_fill_distiller(palette = "Spectral", limits = c(min(-2), max(2)))

2)I plot d2:
gp<- ggplot(d2, aes(x=variable, y=car_percentage, fill=log_median)) + 
  geom_bar(position="dodge", stat="identity", color="black") +
  labs(x="", y = "car percentage", fill="Log (median)") +
  scale_fill_distiller(palette = "Spectral", limits = c(min(-2), max(2)))

then, i want to compare both so I want them both in the same plot. I also want the numbers to match so I have to add the missing values but I don't know how to automate it, because now I have to go to each plot see what are the differences and add the manually with:

A= add_row(d1, variable= "79", log_median=0, car_percentage=0) ... and so on for d1
B= add_row(d2, variable= "17", log_median=0, car_percentage=0) ... and so on for d2.

Now, I want to plot A and B on the sample plot with each conserving the fill scale for log_median. So i added a column called DS (for dataset) and merged A and B:

A["DS"] <- NA
A$"DS" <- "  d1"

B["DS"] <- NA
B$"DS" <- "  d2"

final= rbind(B, A)

then, I try to plot the final file with:

gp2<- ggplot(final_all, aes(x=variable, y=car_percentage, fill=log_median)) + 
  geom_bar(position="dodge", stat="identity", color="black") +
  geom_text( aes(label = paste0(DS, ":\n", round((car_percentage*100),2), "%")), size=2)+
  labs(x="", y = "car percentage", fill="Log (median)") +
  scale_fill_distiller(palette = "Spectral", limits = c(min(-2), max(2)))+
 
but my graph is all messed up:
- the bars are stacked instead of dodge
- the values are written outside the bars and it is difficult to follow what is what.
- sometimes i don't see two data stacked and rather i see only one bar (given that one is hiding the other).

Can anyone please help?
many thanks :)))

**Comment by MariaZhi** [comment]
any help with the script at least?

**Comment by nokome** [comment]
Hey @MariaZhi :wave: sorry for the delayed response (busy times :running_man: ) I'll try to help out later today.

**Comment by nokome** [comment]
Hi, this is the best I could come up with given the time I have available. I added `group=DS` to get dodging to work and rotated the labels so that they are a little more visible. Hope that is of use.

```r
library(ggplot2)

d1 <- read.table(header=T, text = 'variable	log_median	car_percentage
1	-0.9133612	1
2	-1.0603856	0.83810888
3	-0.1779693	0.4713467
5	-0.3073219	1
8	-0.0652583	0.01862464
9	-0.2850852	0.00573066
13	-1.0128372	0.83381089
17	-1.1453479	0.02005731
18	-0.9076425	0.4713467
21	0.286662	0.00143266
26	0.33405882	0.00573066
')

d2 <- read.table(header=T, text = 'variable	log_median	car_percentage
1	0.43073252	0.09090909
2	0.30946316	0.39772727
3	0.2369125	0.28977273
5	0.15575268	0.48863636
10	1.72587962	0.00568182
13	0.31361912	0.36931818
19	0.99486036	0.00568182
26	1.22286942	0.00568182
45	0.22184875	0.01136364
79	0.02882633	0.01136364
')

all <- rbind(
  within(d1, {DS <- 'd1'}),
  within(d2, {DS <- 'd2'})
)

ggplot(all, aes(x=variable, y=car_percentage, fill=log_median, group=DS)) +
  geom_col(position="dodge", color="black") +
  geom_text(aes(label = paste0(DS, ":", round((car_percentage*100),2), "%")), angle=90, vjust=0.5, hjust=-0.1, size=3)+
  labs(x="", y = "car percentage", fill="Log (median)") + ylim(0, 1.1) + 
  scale_fill_distiller(palette = "Spectral", limits = c(min(-2), max(2)))
```

![image](https://user-images.githubusercontent.com/1152336/46002710-e1f7aa00-c102-11e8-8055-f82ad3646a0a.png)

**Comment by MariaZhi** [comment]
Hi,

What about the code?
How can I see what are the variables that match and those that do not match between my two datasets?
And how to automatically add them to each dataset?

Thanks,
Maria


On Sep 25, 2018, at 1:39 AM, Nokome Bentley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi, this is the best I could come up with given the time I have available. I added group=DS to get dodging to work and rotated the labels so that they are a little more visible. Hope that is of use.

library(ggplot2)

d1 <- read.table(header=T, text = 'variable     log_median      car_percentage
1       -0.9133612      1
2       -1.0603856      0.83810888
3       -0.1779693      0.4713467
5       -0.3073219      1
8       -0.0652583      0.01862464
9       -0.2850852      0.00573066
13      -1.0128372      0.83381089
17      -1.1453479      0.02005731
18      -0.9076425      0.4713467
21      0.286662        0.00143266
26      0.33405882      0.00573066
')

d2 <- read.table(header=T, text = 'variable     log_median      car_percentage
1       0.43073252      0.09090909
2       0.30946316      0.39772727
3       0.2369125       0.28977273
5       0.15575268      0.48863636
10      1.72587962      0.00568182
13      0.31361912      0.36931818
19      0.99486036      0.00568182
26      1.22286942      0.00568182
45      0.22184875      0.01136364
79      0.02882633      0.01136364
')

all <- rbind(
  within(d1, {DS <- 'd1'}),
  within(d2, {DS <- 'd2'})
)

ggplot(all, aes(x=variable, y=car_percentage, fill=log_median, group=DS)) +
  geom_col(position="dodge", color="black") +
  geom_text(aes(label = paste0(DS, ":", round((car_percentage*100),2), "%")), angle=90, vjust=0.5, hjust=-0.1, size=3)+
  labs(x="", y = "car percentage", fill="Log (median)") + ylim(0, 1.1) +
  scale_fill_distiller(palette = "Spectral", limits = c(min(-2), max(2)))

[image]<https://user-images.githubusercontent.com/1152336/46002710-e1f7aa00-c102-11e8-8055-f82ad3646a0a.png>
